name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_BOT_TOKEN }}

      - name: Prepare repository
        run: git fetch --prune --tags

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=nvmrc::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
          cache: npm

      - name: Install 🔧
        run: npm ci --legacy-peer-deps

      - name: Create Release ✨
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: npx auto shipit
